#!/bin/bash
# Railway Deployment Commands
# Run these commands after creating GitHub repository

echo "🚀 Railway Deployment Commands"
echo ""
echo "Step 1: Create GitHub Repository"
echo "   Go to: https://github.com/new"
echo "   Repository name: facial-emotion-project"
echo "   DO NOT initialize with README"
echo "   Click 'Create repository'"
echo ""
echo "Step 2: Run these commands (replace YOUR_USERNAME and REPO_NAME):"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/REPO_NAME.git"
echo "git push -u origin main"
echo ""
echo "Step 3: Deploy on Railway"
echo "   1. Go to https://railway.app"
echo "   2. Sign up with GitHub"
echo "   3. New Project → Deploy from GitHub repo"
echo "   4. Select your repository"
echo ""
echo "Step 4: Set Environment Variables in Railway"
echo "   Backend service → Variables tab:"
echo "   PORT=5001"
echo "   PY_API=http://emotion-ai:8000/analyze"
echo "   MONGO_URI=mongodb+srv://adeshsiddhartha2005_db:Adesh141@cluster0.ap8scd3.mongodb.net/emotiondb?retryWrites=true&w=majority"
echo "   NODE_ENV=production"
echo ""
echo "Step 5: Get Public URL"
echo "   Frontend service → Settings → Generate Domain"
echo "   You'll get: https://your-app.railway.app"
echo ""
echo "✅ Done! Your app is live and accessible from anywhere!"

